CREATE TABLE IDS  (
  TABLE_NAME varchar(60) NOT NULL,
  NEXT_ID numeric(30,0)DEFAULT 0 NOT NULL ,
  CONSTRAINT IDS_PK PRIMARY KEY (TABLE_NAME)
);

CREATE TABLE COMTECOPSEQ  (
  TABLE_NAME varchar(60) NOT NULL,
  NEXT_ID numeric(30,0)DEFAULT 0 NOT NULL ,
  CONSTRAINT COMTECOPSEQ_PK PRIMARY KEY (TABLE_NAME)
);

CREATE TABLE TB_CMMN_CL_CODE (
  CL_CODE char(3) NOT NULL,
  CL_CODE_NM varchar(180) ,
  CL_CODE_DC varchar(600) ,
  USE_AT char(1) ,
  FRST_REGIST_PNTTM DATETIME ,
  FRST_REGISTER_ID varchar(60) ,
  LAST_UPDT_PNTTM DATETIME ,
  LAST_UPDUSR_ID varchar(60) ,
  CONSTRAINT TB_CMMN_CL_CODE_PK PRIMARY KEY (CL_CODE)
) ;

CREATE TABLE TB_CMMN_CODE  (
  CODE_ID varchar(18) NOT NULL,
  CODE_ID_NM varchar(180) ,
  CODE_ID_DC varchar(600) ,
  USE_AT char(1) ,
  CL_CODE char(3) ,
  FRST_REGIST_PNTTM DATETIME ,
  FRST_REGISTER_ID varchar(60) ,
  LAST_UPDT_PNTTM DATETIME ,
  LAST_UPDUSR_ID varchar(60) ,
  CONSTRAINT TB_CMMN_CODE_PK PRIMARY KEY (CODE_ID),
  CONSTRAINT TB_CMMN_CODE_ibfk_1 FOREIGN KEY (CL_CODE) REFERENCES TB_CMMN_CL_CODE (CL_CODE)
) ;

CREATE TABLE TB_CMMN_DETAIL_CODE  (
  CODE_ID varchar(18) NOT NULL,
  CODE varchar(45) NOT NULL,
  CODE_NM varchar(180) ,
  CODE_DC varchar(600) ,
  USE_AT char(1) ,
  FRST_REGIST_PNTTM DATETIME ,
  FRST_REGISTER_ID varchar(60) ,
  LAST_UPDT_PNTTM DATETIME ,
  LAST_UPDUSR_ID varchar(60) ,
  CONSTRAINT TB_CMMN_DETAIL_CODE_PK PRIMARY KEY (CODE_ID,CODE),
  CONSTRAINT TB_CMMN_DETAIL_CODE_ibfk_1 FOREIGN KEY (CODE_ID) REFERENCES TB_CMMN_CODE (CODE_ID)
) ;

CREATE TABLE TB_EMPLYR_INFO_CHNG_DTLS (
  EMPLYR_ID     VARCHAR(20) NOT NULL,
  CHANGE_DE     CHAR(20)    NOT NULL,
  ORGNZT_ID     CHAR(20),
  GROUP_ID      CHAR(20),
  EMPL_NO       VARCHAR(20) NOT NULL,
  SEXDSTN_CODE  CHAR(1),
  BRTHDY        CHAR(20),
  FXNUM         VARCHAR(20),
  HOUSE_ADRES   VARCHAR(100) NOT NULL,
  HOUSE_END_TELNO VARCHAR(4),
  AREA_NO       VARCHAR(4),
  DETAIL_ADRES  VARCHAR(100) NOT NULL,
  ZIP           VARCHAR(6) NOT NULL,
  OFFM_TELNO    VARCHAR(20),
  MBTLNUM       VARCHAR(20) NOT NULL,
  EMAIL_ADRES   VARCHAR(50),
  HOUSE_MIDDLE_TELNO CHAR(4),
  PSTINST_CODE  CHAR(8),
  EMPLYR_STTUS_CODE VARCHAR(15) NOT NULL,
  ESNTL_ID      CHAR(20),
  FRST_REGIST_PNTTM DATETIME ,
  FRST_REGISTER_ID varchar(60) ,
  LAST_UPDT_PNTTM DATETIME ,
  LAST_UPDUSR_ID varchar(60) ,
  CONSTRAINT TB_EMPLYR_INFO_CHNG_DTLS_PK PRIMARY KEY (EMPLYR_ID, CHANGE_DE),
  CONSTRAINT TB_EMPLYR_INFO_CHNG_DTLS_ibfk_1 FOREIGN KEY (EMPLYR_ID) REFERENCES TB_EMPLYR_INFO(EMPLYR_ID)
) ;


CREATE TABLE TB_ORGNZT_INFO  (
  ORGNZT_ID char(20) DEFAULT '' NOT NULL,
  ORGNZT_NM varchar(60) NOT NULL,
  ORGNZT_DC varchar(300) ,
  FRST_REGIST_PNTTM DATETIME ,
  FRST_REGISTER_ID varchar(60) ,
  LAST_UPDT_PNTTM DATETIME ,
  LAST_UPDUSR_ID varchar(60) ,
  CONSTRAINT TB_ORGNZT_INFO_PK PRIMARY KEY (ORGNZT_ID)
) ;

CREATE TABLE TB_AUTHOR_GROUP_INFO  (
  GROUP_ID char(20) DEFAULT '' NOT NULL,
  GROUP_NM varchar(180) NOT NULL,
  GROUP_CREAT_DE char(60) NOT NULL,
  GROUP_DC varchar(300) ,
  FRST_REGIST_PNTTM DATETIME ,
  FRST_REGISTER_ID varchar(60) ,
  LAST_UPDT_PNTTM DATETIME ,
  LAST_UPDUSR_ID varchar(60) ,
  CONSTRAINT TB_AUTHOR_GROUP_INFO_PK PRIMARY KEY (GROUP_ID)
) ;

CREATE TABLE TB_AUTHOR_INFO (
  AUTHOR_CODE   VARCHAR(30) NOT NULL,
  AUTHOR_NM     VARCHAR(60) NOT NULL,
  AUTHOR_DC     VARCHAR(200),
  AUTHOR_CREAT_DE CHAR(20) NOT NULL,
  FRST_REGIST_PNTTM DATETIME ,
  FRST_REGISTER_ID varchar(60) ,
  LAST_UPDT_PNTTM DATETIME ,
  LAST_UPDUSR_ID varchar(60) ,
  CONSTRAINT TB_AUTHOR_INFO_PK PRIMARY KEY (AUTHOR_CODE)
) ;

CREATE TABLE TB_EMPLYR_INFO  (
  EMPLYR_ID varchar(60) NOT NULL,
  ORGNZT_ID char(20) ,
  USER_NM varchar(180) NOT NULL,
  PASSWORD varchar(600) NOT NULL,
  EMPL_NO varchar(60) ,
  IHIDNUM varchar(39) ,
  SEXDSTN_CODE char(1) ,
  BRTHDY char(20) ,
  FXNUM varchar(60) ,
  HOUSE_ADRES varchar(300) ,
  PASSWORD_HINT varchar(300) NOT NULL,
  PASSWORD_CNSR varchar(300) NOT NULL,
  HOUSE_END_TELNO varchar(12) ,
  AREA_NO varchar(12) ,
  DETAIL_ADRES varchar(300) ,
  ZIP varchar(18) ,
  OFFM_TELNO varchar(60) ,
  MBTLNUM varchar(60) ,
  EMAIL_ADRES varchar(150) ,
  OFCPS_NM varchar(180) ,
  HOUSE_MIDDLE_TELNO varchar(12) ,
  GROUP_ID char(20) ,
  PSTINST_CODE char(8) ,
  EMPLYR_STTUS_CODE varchar(45) NOT NULL,
  ESNTL_ID char(20) NOT NULL,
  CRTFC_DN_VALUE varchar(60) ,
  SBSCRB_DE DATETIME ,
  FRST_REGIST_PNTTM DATETIME ,
  FRST_REGISTER_ID varchar(60) ,
  LAST_UPDT_PNTTM DATETIME ,
  LAST_UPDUSR_ID varchar(60) ,
  CONSTRAINT TB_EMPLYR_INFO_PK PRIMARY KEY (EMPLYR_ID),
  CONSTRAINT TB_EMPLYR_INFO_ibfk_2 FOREIGN KEY (GROUP_ID) REFERENCES TB_AUTHOR_GROUP_INFO (GROUP_ID) ON DELETE CASCADE,
  CONSTRAINT TB_EMPLYR_INFO_ibfk_1 FOREIGN KEY (ORGNZT_ID) REFERENCES TB_ORGNZT_INFO (ORGNZT_ID) ON DELETE CASCADE
) ;

CREATE TABLE TB_EMPLYR_SCRTY_ESTBS (
  SCRTY_DTRMN_TRGET_ID VARCHAR(20) NOT NULL,
  MBER_TY_CODE         VARCHAR(15),
  AUTHOR_CODE          VARCHAR(30) NOT NULL,
  FRST_REGIST_PNTTM DATETIME ,
  FRST_REGISTER_ID varchar(60) ,
  LAST_UPDT_PNTTM DATETIME ,
  LAST_UPDUSR_ID varchar(60) ,
  CONSTRAINT TB_EMPLYR_SCRTY_ESTBS_PK PRIMARY KEY (SCRTY_DTRMN_TRGET_ID),
  CONSTRAINT TB_EMPLYR_SCRTY_ESTBS_ibfk_1 FOREIGN KEY (SCRTY_DTRMN_TRGET_ID) REFERENCES TB_EMPLYR_INFO(EMPLYR_ID),
  CONSTRAINT TB_EMPLYR_SCRTY_ESTBS_ibfk_2 FOREIGN KEY (AUTHOR_CODE) REFERENCES TB_AUTHOR_INFO(AUTHOR_CODE),
  CONSTRAINT TB_EMPLYR_SCRTY_ESTBS_ibfk_3 FOREIGN KEY (SCRTY_DTRMN_TRGET_ID) REFERENCES TB_ENTRPRS_MBER(ENTRPRS_MBER_ID),
  CONSTRAINT TB_EMPLYR_SCRTY_ESTBS_ibfk_4 FOREIGN KEY (SCRTY_DTRMN_TRGET_ID) REFERENCES TB_GNRL_MBER(MBER_ID)
);

CREATE TABLE TB_BBS_MASTER  (
  BBS_ID char(20) NOT NULL,
  BBS_NM varchar(765) NOT NULL,
  BBS_INTRCN varchar(7200) ,
  BBS_TY_CODE char(6) NOT NULL,
  BBS_ATTRB_CODE char(6) NOT NULL,
  REPLY_POSBL_AT char(1) ,
  FILE_ATCH_POSBL_AT char(1) NOT NULL,
  ATCH_POSBL_FILE_NUMBER numeric(2,0) NOT NULL,
  ATCH_POSBL_FILE_SIZE numeric(8,0) ,
  USE_AT char(1) NOT NULL,
  TMPLAT_ID char(20) ,
  FRST_REGISTER_ID varchar(60) NOT NULL,
  FRST_REGIST_PNTTM DATETIME NOT NULL,
  LAST_UPDUSR_ID varchar(60) ,
  LAST_UPDT_PNTTM DATETIME ,
  CONSTRAINT TB_BBS_MASTER_PK PRIMARY KEY (BBS_ID)
) ;

CREATE TABLE TB_BBS_USE  (
  BBS_ID char(20) NOT NULL,
  TRGET_ID char(20) DEFAULT '' NOT NULL,
  USE_AT char(1) NOT NULL,
  REGIST_SE_CODE char(6) ,
  FRST_REGIST_PNTTM DATETIME ,
  FRST_REGISTER_ID varchar(60) NOT NULL,
  LAST_UPDT_PNTTM DATETIME ,
  LAST_UPDUSR_ID varchar(60) ,
  CONSTRAINT TB_BBS_USE_PK PRIMARY KEY (BBS_ID,TRGET_ID),
  CONSTRAINT TB_BBS_USE_ibfk_1 FOREIGN KEY (BBS_ID) REFERENCES TB_BBS_MASTER (BBS_ID)
) ;

CREATE TABLE TB_BBS (
  NTT_ID numeric(20,0) NOT NULL,
  BBS_ID char(20) NOT NULL,
  NTT_NO numeric(20,0) ,
  NTT_SJ varchar(6000) ,
  NTT_CN STRING,
  ANSWER_AT char(1) ,
  PARNTSCTT_NO numeric(10,0) ,
  ANSWER_LC numeric(11) ,
  SORT_ORDR numeric(8,0) ,
  RDCNT numeric(10,0) ,
  USE_AT char(1) NOT NULL,
  NTCE_BGNDE char(20) ,
  NTCE_ENDDE char(20) ,
  NTCR_ID varchar(60) ,
  NTCR_NM varchar(60) ,
  PASSWORD varchar(600) ,
  ATCH_FILE_ID char(20) ,
  FRST_REGIST_PNTTM DATETIME NOT NULL,
  FRST_REGISTER_ID varchar(60) NOT NULL,
  LAST_UPDT_PNTTM DATETIME ,
  LAST_UPDUSR_ID varchar(60) ,
  CONSTRAINT TB_BBS_PK PRIMARY KEY (NTT_ID,BBS_ID),
  CONSTRAINT TB_BBS_ibfk_1 FOREIGN KEY (BBS_ID) REFERENCES TB_BBS_MASTER (BBS_ID)
) ;

CREATE TABLE TB_BBS_MASTER_OPTN (
  BBS_ID char(20) DEFAULT '' NOT NULL,
  ANSWER_AT char(1) DEFAULT '' NOT NULL,
  STSFDG_AT char(1) DEFAULT '' NOT NULL,
  FRST_REGIST_PNTTM DATETIME DEFAULT SYSDATE NOT NULL,
  LAST_UPDT_PNTTM DATETIME ,
  FRST_REGISTER_ID varchar(60) DEFAULT '' NOT NULL,
  LAST_UPDUSR_ID varchar(60) ,
  CONSTRAINT TB_BBS_MASTER_OPTN_PK PRIMARY KEY (BBS_ID)
) ;

CREATE TABLE TB_ENTRPRS_MBER (
  ENTRPRS_MBER_ID varchar(60) DEFAULT '' NOT NULL,
  ENTRPRS_SE_CODE char(15) ,
  BIZRNO varchar(30) ,
  JURIRNO varchar(39) ,
  CMPNY_NM varchar(180) NOT NULL,
  CXFC varchar(150) ,
  ZIP varchar(18) ,
  ADRES varchar(300) ,
  ENTRPRS_MIDDLE_TELNO varchar(12) ,
  FXNUM varchar(60) ,
  INDUTY_CODE char(15) ,
  APPLCNT_NM varchar(150) NOT NULL,
  APPLCNT_IHIDNUM varchar(39) ,
  SBSCRB_DE DATETIME ,
  ENTRPRS_MBER_STTUS varchar(45) ,
  ENTRPRS_MBER_PASSWORD varchar(600) NOT NULL,
  ENTRPRS_MBER_PASSWORD_HINT varchar(300) NOT NULL,
  ENTRPRS_MBER_PASSWORD_CNSR varchar(300) NOT NULL,
  GROUP_ID char(20) ,
  DETAIL_ADRES varchar(300) ,
  ENTRPRS_END_TELNO varchar(12) ,
  AREA_NO varchar(12) ,
  APPLCNT_EMAIL_ADRES varchar(150) ,
  ESNTL_ID char(20) NOT NULL,
  FRST_REGIST_PNTTM DATETIME ,
  FRST_REGISTER_ID varchar(60) ,
  LAST_UPDT_PNTTM DATETIME ,
  LAST_UPDUSR_ID varchar(60) ,
  CONSTRAINT TB_ENTRPRS_MBER_PK PRIMARY KEY (ENTRPRS_MBER_ID),
  CONSTRAINT TB_ENTRPRS_MBER_ibfk_1 FOREIGN KEY (GROUP_ID) REFERENCES TB_AUTHOR_GROUP_INFO (GROUP_ID) ON DELETE CASCADE
) ;

CREATE TABLE TB_FILE (
  ATCH_FILE_ID char(20) NOT NULL,
  CREAT_DT DATETIME NOT NULL,
  USE_AT char(1) ,
  FRST_REGIST_PNTTM DATETIME ,
  FRST_REGISTER_ID varchar(60) ,
  LAST_UPDT_PNTTM DATETIME ,
  LAST_UPDUSR_ID varchar(60) ,
  CONSTRAINT TB_FILE_PK PRIMARY KEY (ATCH_FILE_ID)
) ;

CREATE TABLE TB_FILE_DETAIL (
  ATCH_FILE_ID char(20) NOT NULL,
  FILE_SN numeric(10,0) NOT NULL,
  FILE_STRE_COURS varchar(6000) NOT NULL,
  STRE_FILE_NM varchar(765) NOT NULL,
  ORIGNL_FILE_NM varchar(765) ,
  FILE_EXTSN varchar(60) NOT NULL,
  FILE_CN STRING,
  FILE_SIZE numeric(8,0) ,
  FRST_REGIST_PNTTM DATETIME ,
  FRST_REGISTER_ID varchar(60) ,
  LAST_UPDT_PNTTM DATETIME ,
  LAST_UPDUSR_ID varchar(60) ,
  CONSTRAINT TB_FILE_DETAIL_PK PRIMARY KEY (ATCH_FILE_ID,FILE_SN),
  CONSTRAINT TB_FILE_DETAIL_ibfk_1 FOREIGN KEY (ATCH_FILE_ID) REFERENCES TB_FILE (ATCH_FILE_ID)
) ;

CREATE TABLE TB_GNRL_MBER (
  MBER_ID varchar(60) DEFAULT '' NOT NULL,
  PASSWORD varchar(600) NOT NULL,
  PASSWORD_HINT varchar(300) NOT NULL,
  PASSWORD_CNSR varchar(300) NOT NULL,
  IHIDNUM varchar(39) ,
  MBER_NM varchar(150) NOT NULL,
  ZIP varchar(18) ,
  ADRES varchar(300) ,
  AREA_NO varchar(12) ,
  MBER_STTUS varchar(45) ,
  DETAIL_ADRES varchar(300) ,
  END_TELNO varchar(12) ,
  MBTLNUM varchar(60) ,
  GROUP_ID char(20) ,
  MBER_FXNUM varchar(60) ,
  MBER_EMAIL_ADRES varchar(150) ,
  MIDDLE_TELNO varchar(12) ,
  SBSCRB_DE DATETIME ,
  SEXDSTN_CODE char(1) ,
  ESNTL_ID char(20) NOT NULL,
  FRST_REGIST_PNTTM DATETIME ,
  FRST_REGISTER_ID varchar(60) ,
  LAST_UPDT_PNTTM DATETIME ,
  LAST_UPDUSR_ID varchar(60) ,
  CONSTRAINT TB_GNRL_MBER_PK PRIMARY KEY (MBER_ID),
  CONSTRAINT TB_GNRL_MBER_ibfk_1 FOREIGN KEY (GROUP_ID) REFERENCES TB_AUTHOR_GROUP_INFO (GROUP_ID) ON DELETE CASCADE
) ;

CREATE TABLE TB_SCHDUL_INFO (
  SCHDUL_ID char(20) NOT NULL,
  SCHDUL_SE char(1) ,
  SCHDUL_DEPT_ID varchar(60) ,
  SCHDUL_KND_CODE varchar(60) ,
  SCHDUL_BEGINDE char(40) ,
  SCHDUL_ENDDE char(40) ,
  SCHDUL_NM varchar(765) ,
  SCHDUL_CN varchar(7500) ,
  SCHDUL_PLACE varchar(765) ,
  SCHDUL_IPCR_CODE char(1) ,
  SCHDUL_CHARGER_ID varchar(60) ,
  ATCH_FILE_ID char(20) ,
  FRST_REGIST_PNTTM DATETIME ,
  FRST_REGISTER_ID varchar(60) ,
  LAST_UPDT_PNTTM DATETIME ,
  LAST_UPDUSR_ID varchar(60) ,
  REPTIT_SE_CODE char(3) ,
  CONSTRAINT TB_SCHDUL_INFO_PK PRIMARY KEY (SCHDUL_ID)
) ;
CREATE OR REPLACE VIEW VW_USER_MASTER ( ESNTL_ID,USER_ID,PASSWORD,USER_NM,USER_ZIP,USER_ADRES,USER_EMAIL,GROUP_ID, USER_SE, ORGNZT_ID )
AS
        SELECT ESNTL_ID, MBER_ID,PASSWORD,MBER_NM,ZIP,ADRES,MBER_EMAIL_ADRES,' ','GNR' AS USER_SE, ' ' ORGNZT_ID
        FROM TB_GNRL_MBER
    UNION ALL
        SELECT ESNTL_ID,EMPLYR_ID,PASSWORD,USER_NM,ZIP,HOUSE_ADRES,EMAIL_ADRES,GROUP_ID ,'USR' AS USER_SE, ORGNZT_ID
        FROM TB_EMPLYR_INFO
    UNION ALL
        SELECT ESNTL_ID,ENTRPRS_MBER_ID,ENTRPRS_MBER_PASSWORD,CMPNY_NM,ZIP,ADRES,APPLCNT_EMAIL_ADRES,' ' ,'ENT' AS USER_SE, ' ' ORGNZT_ID
        FROM TB_ENTRPRS_MBER
;

-- 커뮤니티/동호회/약관/다이어리 (기능 유지 — 표준 TB_ 명명 + 감사컬럼)
DROP TABLE IF EXISTS TB_CMMNTY_USER;
DROP TABLE IF EXISTS TB_CLUB_USER;
DROP TABLE IF EXISTS TB_CMMNTY;
DROP TABLE IF EXISTS TB_CLUB;
DROP TABLE IF EXISTS TB_STPLAT_INFO;
DROP TABLE IF EXISTS TB_DIARY_INFO;
CREATE TABLE TB_CMMNTY (
  CMMNTY_ID varchar(20) NOT NULL,
  CMMNTY_NM varchar(180) ,
  USE_AT char(1) ,
  FRST_REGIST_PNTTM DATETIME , FRST_REGISTER_ID varchar(60) , LAST_UPDT_PNTTM DATETIME , LAST_UPDUSR_ID varchar(60) ,
  CONSTRAINT TB_CMMNTY_PK PRIMARY KEY (CMMNTY_ID)
) ;
CREATE TABLE TB_CMMNTY_USER (
  ESNTL_ID varchar(20) NOT NULL,
  CMMNTY_ID varchar(20) ,
  EMPLYR_ID varchar(20) ,
  MNGR_AT char(1) ,
  USE_AT char(1) ,
  REGIST_SE_CODE varchar(18) ,
  FRST_REGIST_PNTTM DATETIME , FRST_REGISTER_ID varchar(60) , LAST_UPDT_PNTTM DATETIME , LAST_UPDUSR_ID varchar(60) ,
  CONSTRAINT TB_CMMNTY_USER_PK PRIMARY KEY (ESNTL_ID)
) ;
CREATE TABLE TB_CLUB (
  CLB_ID varchar(20) NOT NULL,
  CLB_NM varchar(180) ,
  USE_AT char(1) ,
  FRST_REGIST_PNTTM DATETIME , FRST_REGISTER_ID varchar(60) , LAST_UPDT_PNTTM DATETIME , LAST_UPDUSR_ID varchar(60) ,
  CONSTRAINT TB_CLUB_PK PRIMARY KEY (CLB_ID)
) ;
CREATE TABLE TB_CLUB_USER (
  ESNTL_ID varchar(20) NOT NULL,
  CLB_ID varchar(20) ,
  EMPLYR_ID varchar(20) ,
  OPRTR_AT char(1) ,
  USE_AT char(1) ,
  REGIST_SE_CODE varchar(18) ,
  FRST_REGIST_PNTTM DATETIME , FRST_REGISTER_ID varchar(60) , LAST_UPDT_PNTTM DATETIME , LAST_UPDUSR_ID varchar(60) ,
  CONSTRAINT TB_CLUB_USER_PK PRIMARY KEY (ESNTL_ID)
) ;
CREATE TABLE TB_STPLAT_INFO (
  USE_STPLAT_ID varchar(20) NOT NULL,
  USE_STPLAT_NM varchar(300) ,
  USE_STPLAT_CN varchar(12000) ,
  INFO_PROVD_AGRE_CN varchar(12000) ,
  FRST_REGIST_PNTTM DATETIME , FRST_REGISTER_ID varchar(60) , LAST_UPDT_PNTTM DATETIME , LAST_UPDUSR_ID varchar(60) ,
  CONSTRAINT TB_STPLAT_INFO_PK PRIMARY KEY (USE_STPLAT_ID)
) ;
CREATE TABLE TB_DIARY_INFO (
  DIARY_ID varchar(20) NOT NULL,
  SCHDUL_ID varchar(20) ,
  DIARY_CN varchar(7500) ,
  FRST_REGIST_PNTTM DATETIME , FRST_REGISTER_ID varchar(60) , LAST_UPDT_PNTTM DATETIME , LAST_UPDUSR_ID varchar(60) ,
  CONSTRAINT TB_DIARY_INFO_PK PRIMARY KEY (DIARY_ID)
) ;

-- 개정이력: 2026.06.17  구재호  커뮤니티/동호회/약관/다이어리 TB_ 테이블 추가
