DROP TABLE IDS CASCADE CONSTRAINTS;
CREATE TABLE IDS  (
  TABLE_NAME varchar2(20) NOT NULL,
  NEXT_ID number(30,0)DEFAULT 0 NOT NULL ,
  CONSTRAINT IDS_PK PRIMARY KEY (TABLE_NAME)
);
DROP TABLE COMTECOPSEQ CASCADE CONSTRAINTS;
CREATE TABLE COMTECOPSEQ  (
  TABLE_NAME varchar2(20) NOT NULL,
  NEXT_ID number(30,0)DEFAULT 0 NOT NULL ,
  CONSTRAINT COMTECOPSEQ_PK PRIMARY KEY (TABLE_NAME)
);
DROP TABLE TB_CMMN_CL_CODE CASCADE CONSTRAINTS;
CREATE TABLE TB_CMMN_CL_CODE (
  CL_CODE char(3) NOT NULL,
  CL_CODE_NM varchar2(60) ,
  CL_CODE_DC varchar2(200) ,
  USE_AT char(1) ,
  FRST_REGIST_PNTTM DATE ,
  FRST_REGISTER_ID varchar2(20) ,
  LAST_UPDT_PNTTM DATE ,
  LAST_UPDUSR_ID varchar2(20) ,
  CONSTRAINT TB_CMMN_CL_CODE_PK PRIMARY KEY (CL_CODE)
) ;
DROP TABLE TB_CMMN_CODE CASCADE CONSTRAINTS;
CREATE TABLE TB_CMMN_CODE  (
  CODE_ID varchar2(6) NOT NULL,
  CODE_ID_NM varchar2(60) ,
  CODE_ID_DC varchar2(200) ,
  USE_AT char(1) ,
  CL_CODE char(3) ,
  FRST_REGIST_PNTTM DATE ,
  FRST_REGISTER_ID varchar2(20) ,
  LAST_UPDT_PNTTM DATE ,
  LAST_UPDUSR_ID varchar2(20) ,
  CONSTRAINT TB_CMMN_CODE_PK PRIMARY KEY (CODE_ID),
  CONSTRAINT TB_CMMN_CODE_ibfk_1 FOREIGN KEY (CL_CODE) REFERENCES TB_CMMN_CL_CODE (CL_CODE)
) ;
DROP TABLE TB_CMMN_DETAIL_CODE CASCADE CONSTRAINTS;
CREATE TABLE TB_CMMN_DETAIL_CODE  (
  CODE_ID varchar2(6) NOT NULL,
  CODE varchar2(15) NOT NULL,
  CODE_NM varchar2(60) ,
  CODE_DC varchar2(200) ,
  USE_AT char(1) ,
  FRST_REGIST_PNTTM DATE ,
  FRST_REGISTER_ID varchar2(20) ,
  LAST_UPDT_PNTTM DATE ,
  LAST_UPDUSR_ID varchar2(20) ,
  CONSTRAINT TB_CMMN_DETAIL_CODE_PK PRIMARY KEY (CODE_ID,CODE),
  CONSTRAINT TB_CMMN_DETAIL_CODE_ibfk_1 FOREIGN KEY (CODE_ID) REFERENCES TB_CMMN_CODE (CODE_ID)
) ;

DROP TABLE TB_EMPLYR_INFO_CHNG_DTLS CASCADE CONSTRAINTS;
CREATE TABLE TB_EMPLYR_INFO_CHNG_DTLS (
    EMPLYR_ID     VARCHAR2(20)  NOT NULL,
    CHANGE_DE     CHAR(20)      NOT NULL,
    ORGNZT_ID     CHAR(20),
    GROUP_ID      CHAR(20),
    EMPL_NO       VARCHAR2(20)  NOT NULL,
    SEXDSTN_CODE  CHAR(1),
    BRTHDY        CHAR(20),
    FXNUM         VARCHAR2(20),
    HOUSE_ADRES   VARCHAR2(100) NOT NULL,
    HOUSE_END_TELNO CHAR(4),
    AREA_NO       CHAR(4),
    DETAIL_ADRES  VARCHAR2(100) NOT NULL,
    ZIP           VARCHAR2(6)   NOT NULL,
    OFFM_TELNO    VARCHAR2(20),
    MBTLNUM       VARCHAR2(20)  NOT NULL,
    EMAIL_ADRES   VARCHAR2(50),
    HOUSE_MIDDLE_TELNO CHAR(4),
    PSTINST_CODE  CHAR(8),
    EMPLYR_STTUS_CODE VARCHAR2(15) NOT NULL,
    ESNTL_ID      CHAR(20),
  FRST_REGIST_PNTTM DATE ,
  FRST_REGISTER_ID varchar2(20) ,
  LAST_UPDT_PNTTM DATE ,
  LAST_UPDUSR_ID varchar2(20) ,
    CONSTRAINT TB_EMPLYR_INFO_CHNG_DTLS_PK PRIMARY KEY (EMPLYR_ID, CHANGE_DE),
    CONSTRAINT TB_EMPLYR_INFO_CHNG_DTLS_ibfk_1 FOREIGN KEY (EMPLYR_ID) REFERENCES TB_EMPLYR_INFO(EMPLYR_ID)
);

DROP TABLE TB_ORGNZT_INFO CASCADE CONSTRAINTS;
CREATE TABLE TB_ORGNZT_INFO  (
  ORGNZT_ID char(20) DEFAULT '' NOT NULL,
  ORGNZT_NM varchar2(20) NOT NULL,
  ORGNZT_DC varchar2(100) ,
  FRST_REGIST_PNTTM DATE ,
  FRST_REGISTER_ID varchar2(20) ,
  LAST_UPDT_PNTTM DATE ,
  LAST_UPDUSR_ID varchar2(20) ,
  CONSTRAINT TB_ORGNZT_INFO_PK PRIMARY KEY (ORGNZT_ID)
) ;
DROP TABLE TB_AUTHOR_GROUP_INFO CASCADE CONSTRAINTS;
CREATE TABLE TB_AUTHOR_GROUP_INFO  (
  GROUP_ID char(20) DEFAULT '' NOT NULL,
  GROUP_NM varchar2(60) NOT NULL,
  GROUP_CREAT_DE char(20) NOT NULL,
  GROUP_DC varchar2(100) ,
  FRST_REGIST_PNTTM DATE ,
  FRST_REGISTER_ID varchar2(20) ,
  LAST_UPDT_PNTTM DATE ,
  LAST_UPDUSR_ID varchar2(20) ,
  CONSTRAINT TB_AUTHOR_GROUP_INFO_PK PRIMARY KEY (GROUP_ID)
) ;
DROP TABLE TB_AUTHOR_INFO CASCADE CONSTRAINTS;
CREATE TABLE TB_AUTHOR_INFO (
  AUTHOR_CODE   VARCHAR2(30) NOT NULL,
  AUTHOR_NM     VARCHAR2(60) NOT NULL,
  AUTHOR_DC     VARCHAR2(200),
  AUTHOR_CREAT_DE CHAR(20) NOT NULL,
  FRST_REGIST_PNTTM DATE ,
  FRST_REGISTER_ID varchar2(20) ,
  LAST_UPDT_PNTTM DATE ,
  LAST_UPDUSR_ID varchar2(20) ,
  CONSTRAINT TB_AUTHOR_INFO_PK PRIMARY KEY (AUTHOR_CODE)
);
DROP TABLE TB_EMPLYR_INFO CASCADE CONSTRAINTS;
CREATE TABLE TB_EMPLYR_INFO  (
  EMPLYR_ID varchar2(20) NOT NULL,
  ORGNZT_ID char(20) ,
  USER_NM varchar2(60) NOT NULL,
  PASSWORD varchar2(200) NOT NULL,
  EMPL_NO varchar2(20) ,
  IHIDNUM varchar2(200) ,
  SEXDSTN_CODE char(1) ,
  BRTHDY char(20) ,
  FXNUM varchar2(20) ,
  HOUSE_ADRES varchar2(100) ,
  PASSWORD_HINT varchar2(100) NOT NULL,
  PASSWORD_CNSR varchar2(100) NOT NULL,
  HOUSE_END_TELNO varchar2(4) ,
  AREA_NO varchar2(4) ,
  DETAIL_ADRES varchar2(100) ,
  ZIP varchar2(6) ,
  OFFM_TELNO varchar2(20) ,
  MBTLNUM varchar2(20) ,
  EMAIL_ADRES varchar2(50) ,
  OFCPS_NM varchar2(60) ,
  HOUSE_MIDDLE_TELNO varchar2(4) ,
  GROUP_ID char(20) ,
  PSTINST_CODE char(8) ,
  EMPLYR_STTUS_CODE varchar2(15) NOT NULL,
  ESNTL_ID char(20) NOT NULL,
  CRTFC_DN_VALUE varchar2(20) ,
  SBSCRB_DE DATE ,
  FRST_REGIST_PNTTM DATE ,
  FRST_REGISTER_ID varchar2(20) ,
  LAST_UPDT_PNTTM DATE ,
  LAST_UPDUSR_ID varchar2(20) ,
  CONSTRAINT TB_EMPLYR_INFO_PK PRIMARY KEY (EMPLYR_ID),
  CONSTRAINT TB_EMPLYR_INFO_ibfk_2 FOREIGN KEY (GROUP_ID) REFERENCES TB_AUTHOR_GROUP_INFO (GROUP_ID) ON DELETE CASCADE,
  CONSTRAINT TB_EMPLYR_INFO_ibfk_1 FOREIGN KEY (ORGNZT_ID) REFERENCES TB_ORGNZT_INFO (ORGNZT_ID) ON DELETE CASCADE
) ;
DROP TABLE TB_EMPLYR_SCRTY_ESTBS CASCADE CONSTRAINTS;
CREATE TABLE TB_EMPLYR_SCRTY_ESTBS (
  SCRTY_DTRMN_TRGET_ID VARCHAR2(20) NOT NULL,
  MBER_TY_CODE         VARCHAR2(15),
  AUTHOR_CODE          VARCHAR2(30) NOT NULL,
  FRST_REGIST_PNTTM DATE ,
  FRST_REGISTER_ID varchar2(20) ,
  LAST_UPDT_PNTTM DATE ,
  LAST_UPDUSR_ID varchar2(20) ,
  CONSTRAINT TB_EMPLYR_SCRTY_ESTBS_PK PRIMARY KEY (SCRTY_DTRMN_TRGET_ID),
  CONSTRAINT TB_EMPLYR_SCRTY_ESTBS_ibfk_1 FOREIGN KEY (SCRTY_DTRMN_TRGET_ID) REFERENCES TB_EMPLYR_INFO(EMPLYR_ID),
  CONSTRAINT TB_EMPLYR_SCRTY_ESTBS_ibfk_2 FOREIGN KEY (AUTHOR_CODE) REFERENCES TB_AUTHOR_INFO(AUTHOR_CODE),
  CONSTRAINT TB_EMPLYR_SCRTY_ESTBS_ibfk_3 FOREIGN KEY (SCRTY_DTRMN_TRGET_ID) REFERENCES TB_ENTRPRS_MBER(ENTRPRS_MBER_ID),
  CONSTRAINT TB_EMPLYR_SCRTY_ESTBS_ibfk_4 FOREIGN KEY (SCRTY_DTRMN_TRGET_ID) REFERENCES TB_GNRL_MBER(MBER_ID)
);
DROP TABLE TB_BBS_MASTER CASCADE CONSTRAINTS;
CREATE TABLE TB_BBS_MASTER  (
  BBS_ID char(20) NOT NULL,
  BBS_NM varchar2(255) NOT NULL,
  BBS_INTRCN varchar2(2400) ,
  BBS_TY_CODE char(6) NOT NULL,
  BBS_ATTRB_CODE char(6) NOT NULL,
  REPLY_POSBL_AT char(1) ,
  FILE_ATCH_POSBL_AT char(1) NOT NULL,
  ATCH_POSBL_FILE_NUMBER number(2,0) NOT NULL,
  ATCH_POSBL_FILE_SIZE number(8,0) ,
  USE_AT char(1) NOT NULL,
  TMPLAT_ID char(20) ,
  FRST_REGISTER_ID varchar2(20) NOT NULL,
  FRST_REGIST_PNTTM DATE NOT NULL,
  LAST_UPDUSR_ID varchar2(20) ,
  LAST_UPDT_PNTTM DATE ,
  CONSTRAINT TB_BBS_MASTER_PK PRIMARY KEY (BBS_ID)
) ;
DROP TABLE TB_BBS_USE CASCADE CONSTRAINTS;
CREATE TABLE TB_BBS_USE  (
  BBS_ID char(20) NOT NULL,
  TRGET_ID char(20) DEFAULT '' NOT NULL,
  USE_AT char(1) NOT NULL,
  REGIST_SE_CODE char(6) ,
  FRST_REGIST_PNTTM DATE ,
  FRST_REGISTER_ID varchar2(20) NOT NULL,
  LAST_UPDT_PNTTM DATE ,
  LAST_UPDUSR_ID varchar2(20) ,
  CONSTRAINT TB_BBS_USE_PK PRIMARY KEY (BBS_ID,TRGET_ID),
  CONSTRAINT TB_BBS_USE_ibfk_1 FOREIGN KEY (BBS_ID) REFERENCES TB_BBS_MASTER (BBS_ID)
) ;
DROP TABLE TB_BBS CASCADE CONSTRAINTS;
CREATE TABLE TB_BBS (
  NTT_ID number(20,0) NOT NULL,
  BBS_ID char(20) NOT NULL,
  NTT_NO number(20,0) ,
  NTT_SJ varchar2(2000) ,
  NTT_CN CLOB,
  ANSWER_AT char(1) ,
  PARNTSCTT_NO number(10,0) ,
  ANSWER_LC number(11) ,
  SORT_ORDR number(8,0) ,
  RDCNT number(10,0) ,
  USE_AT char(1) NOT NULL,
  NTCE_BGNDE char(20) ,
  NTCE_ENDDE char(20) ,
  NTCR_ID varchar2(20) ,
  NTCR_NM varchar2(20) ,
  PASSWORD varchar2(200) ,
  ATCH_FILE_ID char(20) ,
  FRST_REGIST_PNTTM DATE NOT NULL,
  FRST_REGISTER_ID varchar2(20) NOT NULL,
  LAST_UPDT_PNTTM DATE ,
  LAST_UPDUSR_ID varchar2(20) ,
  CONSTRAINT TB_BBS_PK PRIMARY KEY (NTT_ID,BBS_ID),
  CONSTRAINT TB_BBS_ibfk_1 FOREIGN KEY (BBS_ID) REFERENCES TB_BBS_MASTER (BBS_ID)
) ;
DROP TABLE TB_BBS_MASTER_OPTN CASCADE CONSTRAINTS;
CREATE TABLE TB_BBS_MASTER_OPTN (
  BBS_ID char(20) DEFAULT '' NOT NULL,
  ANSWER_AT char(1) DEFAULT '' NOT NULL,
  STSFDG_AT char(1) DEFAULT '' NOT NULL,
  FRST_REGIST_PNTTM DATE DEFAULT SYSDATE NOT NULL,
  LAST_UPDT_PNTTM DATE ,
  FRST_REGISTER_ID varchar2(20) DEFAULT '' NOT NULL,
  LAST_UPDUSR_ID varchar2(20) ,
  CONSTRAINT TB_BBS_MASTER_OPTN_PK PRIMARY KEY (BBS_ID)
) ;
DROP TABLE TB_ENTRPRS_MBER CASCADE CONSTRAINTS;
CREATE TABLE TB_ENTRPRS_MBER (
  ENTRPRS_MBER_ID varchar2(20) DEFAULT '' NOT NULL,
  ENTRPRS_SE_CODE char(15) ,
  BIZRNO varchar2(10) ,
  JURIRNO varchar2(13) ,
  CMPNY_NM varchar2(60) NOT NULL,
  CXFC varchar2(50) ,
  ZIP varchar2(6) ,
  ADRES varchar2(100) ,
  ENTRPRS_MIDDLE_TELNO varchar2(4) ,
  FXNUM varchar2(20) ,
  INDUTY_CODE char(15) ,
  APPLCNT_NM varchar2(50) NOT NULL,
  APPLCNT_IHIDNUM varchar2(200) ,
  SBSCRB_DE DATE ,
  ENTRPRS_MBER_STTUS varchar2(15) ,
  ENTRPRS_MBER_PASSWORD varchar2(200) NOT NULL,
  ENTRPRS_MBER_PASSWORD_HINT varchar2(100) NOT NULL,
  ENTRPRS_MBER_PASSWORD_CNSR varchar2(100) NOT NULL,
  GROUP_ID char(20) ,
  DETAIL_ADRES varchar2(100) ,
  ENTRPRS_END_TELNO varchar2(4) ,
  AREA_NO varchar2(4) ,
  APPLCNT_EMAIL_ADRES varchar2(50) ,
  ESNTL_ID char(20) NOT NULL,
  FRST_REGIST_PNTTM DATE ,
  FRST_REGISTER_ID varchar2(20) ,
  LAST_UPDT_PNTTM DATE ,
  LAST_UPDUSR_ID varchar2(20) ,
  CONSTRAINT TB_ENTRPRS_MBER_PK PRIMARY KEY (ENTRPRS_MBER_ID),
  CONSTRAINT TB_ENTRPRS_MBER_ibfk_1 FOREIGN KEY (GROUP_ID) REFERENCES TB_AUTHOR_GROUP_INFO (GROUP_ID) ON DELETE CASCADE
) ;
DROP TABLE TB_FILE CASCADE CONSTRAINTS;
CREATE TABLE TB_FILE (
  ATCH_FILE_ID char(20) NOT NULL,
  CREAT_DT DATE NOT NULL,
  USE_AT char(1) ,
  FRST_REGIST_PNTTM DATE ,
  FRST_REGISTER_ID varchar2(20) ,
  LAST_UPDT_PNTTM DATE ,
  LAST_UPDUSR_ID varchar2(20) ,
  CONSTRAINT TB_FILE_PK PRIMARY KEY (ATCH_FILE_ID)
) ;
DROP TABLE TB_FILE_DETAIL CASCADE CONSTRAINTS;
CREATE TABLE TB_FILE_DETAIL (
  ATCH_FILE_ID char(20) NOT NULL,
  FILE_SN number(10,0) NOT NULL,
  FILE_STRE_COURS varchar2(2000) NOT NULL,
  STRE_FILE_NM varchar2(255) NOT NULL,
  ORIGNL_FILE_NM varchar2(255) ,
  FILE_EXTSN varchar2(20) NOT NULL,
  FILE_CN CLOB,
  FILE_SIZE number(8,0) ,
  FRST_REGIST_PNTTM DATE ,
  FRST_REGISTER_ID varchar2(20) ,
  LAST_UPDT_PNTTM DATE ,
  LAST_UPDUSR_ID varchar2(20) ,
  CONSTRAINT TB_FILE_DETAIL_PK PRIMARY KEY (ATCH_FILE_ID,FILE_SN),
  CONSTRAINT TB_FILE_DETAIL_ibfk_1 FOREIGN KEY (ATCH_FILE_ID) REFERENCES TB_FILE (ATCH_FILE_ID)
) ;
DROP TABLE TB_GNRL_MBER CASCADE CONSTRAINTS;
CREATE TABLE TB_GNRL_MBER (
  MBER_ID varchar2(20) DEFAULT '' NOT NULL,
  PASSWORD varchar2(200) NOT NULL,
  PASSWORD_HINT varchar2(100) NOT NULL,
  PASSWORD_CNSR varchar2(100) NOT NULL,
  IHIDNUM varchar2(200) ,
  MBER_NM varchar2(50) NOT NULL,
  ZIP varchar2(6) ,
  ADRES varchar2(100) ,
  AREA_NO varchar2(4) ,
  MBER_STTUS varchar2(15) ,
  DETAIL_ADRES varchar2(100) ,
  END_TELNO varchar2(4) ,
  MBTLNUM varchar2(20) ,
  GROUP_ID char(20) ,
  MBER_FXNUM varchar2(20) ,
  MBER_EMAIL_ADRES varchar2(50) ,
  MIDDLE_TELNO varchar2(4) ,
  SBSCRB_DE DATE ,
  SEXDSTN_CODE char(1) ,
  ESNTL_ID char(20) NOT NULL,
  FRST_REGIST_PNTTM DATE ,
  FRST_REGISTER_ID varchar2(20) ,
  LAST_UPDT_PNTTM DATE ,
  LAST_UPDUSR_ID varchar2(20) ,
  CONSTRAINT TB_GNRL_MBER_PK PRIMARY KEY (MBER_ID),
  CONSTRAINT TB_GNRL_MBER_ibfk_1 FOREIGN KEY (GROUP_ID) REFERENCES TB_AUTHOR_GROUP_INFO (GROUP_ID) ON DELETE CASCADE
) ;
DROP TABLE TB_SCHDUL_INFO CASCADE CONSTRAINTS;
CREATE TABLE TB_SCHDUL_INFO (
  SCHDUL_ID char(20) NOT NULL,
  SCHDUL_SE char(1) ,
  SCHDUL_DEPT_ID varchar2(20) ,
  SCHDUL_KND_CODE varchar2(20) ,
  SCHDUL_BEGINDE  char(20) ,
  SCHDUL_ENDDE  char(20) ,
  SCHDUL_NM varchar2(255) ,
  SCHDUL_CN varchar2(2500) ,
  SCHDUL_PLACE varchar2(255) ,
  SCHDUL_IPCR_CODE char(1) ,
  SCHDUL_CHARGER_ID varchar2(20) ,
  ATCH_FILE_ID char(20) ,
  FRST_REGIST_PNTTM DATE ,
  FRST_REGISTER_ID varchar2(20) ,
  LAST_UPDT_PNTTM DATE ,
  LAST_UPDUSR_ID varchar2(20) ,
  REPTIT_SE_CODE char(3) ,
  CONSTRAINT TB_SCHDUL_INFO_PK PRIMARY KEY (SCHDUL_ID)
) ;
CREATE OR REPLACE VIEW VW_USER_MASTER ( ESNTL_ID,USER_ID,PASSWORD,USER_NM,USER_ZIP,USER_ADRES,USER_EMAIL,GROUP_ID, USER_SE, ORGNZT_ID ) 
AS  
        SELECT ESNTL_ID, MBER_ID,PASSWORD,MBER_NM,ZIP,ADRES,MBER_EMAIL_ADRES,' ','GNR' AS USER_SE, ' ' ORGNZT_ID
        FROM TB_GNRL_MBER
    UNION ALL
        SELECT ESNTL_ID,EMPLYR_ID,PASSWORD,USER_NM,ZIP,HOUSE_ADRES,EMAIL_ADRES,GROUP_ID ,'USR' AS USER_SE, ORGNZT_ID
        FROM TB_EMPLYR_INFO
    UNION ALL
        SELECT ESNTL_ID,ENTRPRS_MBER_ID,ENTRPRS_MBER_PASSWORD,CMPNY_NM,ZIP,ADRES,APPLCNT_EMAIL_ADRES,' ' ,'ENT' AS USER_SE, ' ' ORGNZT_ID
        FROM TB_ENTRPRS_MBER 
;
-- 커뮤니티/동호회/약관/다이어리 (기능 유지 — 표준 TB_ 명명 + 감사컬럼)
DROP TABLE TB_CMMNTY_USER;
DROP TABLE TB_CLUB_USER;
DROP TABLE TB_CMMNTY;
DROP TABLE TB_CLUB;
DROP TABLE TB_STPLAT_INFO;
DROP TABLE TB_DIARY_INFO;
CREATE TABLE TB_CMMNTY (
  CMMNTY_ID varchar2(20) NOT NULL,
  CMMNTY_NM varchar2(60) ,
  USE_AT char(1) ,
  FRST_REGIST_PNTTM DATE , FRST_REGISTER_ID varchar2(20) , LAST_UPDT_PNTTM DATE , LAST_UPDUSR_ID varchar2(20) ,
  CONSTRAINT TB_CMMNTY_PK PRIMARY KEY (CMMNTY_ID)
) ;
CREATE TABLE TB_CMMNTY_USER (
  ESNTL_ID varchar2(20) NOT NULL,
  CMMNTY_ID varchar2(20) ,
  EMPLYR_ID varchar2(20) ,
  MNGR_AT char(1) ,
  USE_AT char(1) ,
  REGIST_SE_CODE varchar2(6) ,
  FRST_REGIST_PNTTM DATE , FRST_REGISTER_ID varchar2(20) , LAST_UPDT_PNTTM DATE , LAST_UPDUSR_ID varchar2(20) ,
  CONSTRAINT TB_CMMNTY_USER_PK PRIMARY KEY (ESNTL_ID)
) ;
CREATE TABLE TB_CLUB (
  CLB_ID varchar2(20) NOT NULL,
  CLB_NM varchar2(60) ,
  USE_AT char(1) ,
  FRST_REGIST_PNTTM DATE , FRST_REGISTER_ID varchar2(20) , LAST_UPDT_PNTTM DATE , LAST_UPDUSR_ID varchar2(20) ,
  CONSTRAINT TB_CLUB_PK PRIMARY KEY (CLB_ID)
) ;
CREATE TABLE TB_CLUB_USER (
  ESNTL_ID varchar2(20) NOT NULL,
  CLB_ID varchar2(20) ,
  EMPLYR_ID varchar2(20) ,
  OPRTR_AT char(1) ,
  USE_AT char(1) ,
  REGIST_SE_CODE varchar2(6) ,
  FRST_REGIST_PNTTM DATE , FRST_REGISTER_ID varchar2(20) , LAST_UPDT_PNTTM DATE , LAST_UPDUSR_ID varchar2(20) ,
  CONSTRAINT TB_CLUB_USER_PK PRIMARY KEY (ESNTL_ID)
) ;
CREATE TABLE TB_STPLAT_INFO (
  USE_STPLAT_ID varchar2(20) NOT NULL,
  USE_STPLAT_NM varchar2(100) ,
  USE_STPLAT_CN CLOB ,
  INFO_PROVD_AGRE_CN CLOB ,
  FRST_REGIST_PNTTM DATE , FRST_REGISTER_ID varchar2(20) , LAST_UPDT_PNTTM DATE , LAST_UPDUSR_ID varchar2(20) ,
  CONSTRAINT TB_STPLAT_INFO_PK PRIMARY KEY (USE_STPLAT_ID)
) ;
CREATE TABLE TB_DIARY_INFO (
  DIARY_ID varchar2(20) NOT NULL,
  SCHDUL_ID varchar2(20) ,
  DIARY_CN varchar2(2500) ,
  FRST_REGIST_PNTTM DATE , FRST_REGISTER_ID varchar2(20) , LAST_UPDT_PNTTM DATE , LAST_UPDUSR_ID varchar2(20) ,
  CONSTRAINT TB_DIARY_INFO_PK PRIMARY KEY (DIARY_ID)
) ;

-- 개정이력: 2026.06.17  구재호  커뮤니티/동호회/약관/다이어리 TB_ 테이블 추가
