-- ============================================================
-- simple-home-boot PostgreSQL DDL
-- 테이블 명명규칙: TB_ + 기능명 (snake_case)
-- 감사 컬럼: FRST_REGIST_PNTTM, FRST_REGISTER_ID, LAST_UPDT_PNTTM, LAST_UPDUSR_ID
-- ============================================================

-- 기존 테이블 삭제 (의존성 역순)
DROP TABLE IF EXISTS TB_FILE_DETAIL CASCADE;
DROP TABLE IF EXISTS TB_FILE CASCADE;
DROP TABLE IF EXISTS TB_SCHDUL_INFO CASCADE;
DROP TABLE IF EXISTS TB_EMPLYR_SCRTY_ESTBS CASCADE;
DROP TABLE IF EXISTS TB_GNRL_MBER CASCADE;
DROP TABLE IF EXISTS TB_ENTRPRS_MBER CASCADE;
DROP TABLE IF EXISTS TB_EMPLYR_INFO_CHNG_DTLS CASCADE;
DROP TABLE IF EXISTS TB_EMPLYR_INFO CASCADE;
DROP TABLE IF EXISTS TB_ORGNZT_INFO CASCADE;
DROP TABLE IF EXISTS TB_BBS_USE CASCADE;
DROP TABLE IF EXISTS TB_BBS_MASTER_OPTN CASCADE;
DROP TABLE IF EXISTS TB_BBS CASCADE;
DROP TABLE IF EXISTS TB_BBS_MASTER CASCADE;
DROP TABLE IF EXISTS TB_CMMN_DETAIL_CODE CASCADE;
DROP TABLE IF EXISTS TB_CMMN_CODE CASCADE;
DROP TABLE IF EXISTS TB_CMMN_CL_CODE CASCADE;
DROP TABLE IF EXISTS TB_AUTHOR_GROUP_INFO CASCADE;
DROP TABLE IF EXISTS TB_AUTHOR_INFO CASCADE;
DROP TABLE IF EXISTS IDS CASCADE;
DROP TABLE IF EXISTS COMTECOPSEQ CASCADE;
DROP VIEW IF EXISTS VW_USER_MASTER;

-- 시퀀스 테이블
CREATE TABLE IDS (
  TABLE_NAME VARCHAR(20) NOT NULL DEFAULT '',
  NEXT_ID    NUMERIC(30) NOT NULL DEFAULT 0,
  CONSTRAINT IDS_PK PRIMARY KEY (TABLE_NAME)
);

CREATE TABLE COMTECOPSEQ (
  TABLE_NAME VARCHAR(20) NOT NULL DEFAULT '',
  NEXT_ID    NUMERIC(30) NOT NULL DEFAULT 0,
  CONSTRAINT COMTECOPSEQ_PK PRIMARY KEY (TABLE_NAME)
);

-- 공통코드 대분류
CREATE TABLE TB_CMMN_CL_CODE (
  CL_CODE           CHAR(3)      NOT NULL,
  CL_CODE_NM        VARCHAR(60),
  CL_CODE_DC        VARCHAR(200),
  USE_AT            CHAR(1),
  FRST_REGIST_PNTTM TIMESTAMP,
  FRST_REGISTER_ID  VARCHAR(20),
  LAST_UPDT_PNTTM   TIMESTAMP,
  LAST_UPDUSR_ID    VARCHAR(20),
  CONSTRAINT TB_CMMN_CL_CODE_PK PRIMARY KEY (CL_CODE)
);

-- 공통코드 중분류
CREATE TABLE TB_CMMN_CODE (
  CODE_ID           VARCHAR(6)   NOT NULL,
  CODE_ID_NM        VARCHAR(60),
  CODE_ID_DC        VARCHAR(200),
  USE_AT            CHAR(1),
  CL_CODE           CHAR(3),
  FRST_REGIST_PNTTM TIMESTAMP,
  FRST_REGISTER_ID  VARCHAR(20),
  LAST_UPDT_PNTTM   TIMESTAMP,
  LAST_UPDUSR_ID    VARCHAR(20),
  CONSTRAINT TB_CMMN_CODE_PK PRIMARY KEY (CODE_ID),
  CONSTRAINT FK_CMMN_CODE_CL FOREIGN KEY (CL_CODE) REFERENCES TB_CMMN_CL_CODE (CL_CODE)
);

-- 공통코드 소분류
CREATE TABLE TB_CMMN_DETAIL_CODE (
  CODE_ID           VARCHAR(6)   NOT NULL,
  CODE              VARCHAR(15)  NOT NULL,
  CODE_NM           VARCHAR(60),
  CODE_DC           VARCHAR(200),
  USE_AT            CHAR(1),
  FRST_REGIST_PNTTM TIMESTAMP,
  FRST_REGISTER_ID  VARCHAR(20),
  LAST_UPDT_PNTTM   TIMESTAMP,
  LAST_UPDUSR_ID    VARCHAR(20),
  CONSTRAINT TB_CMMN_DETAIL_CODE_PK PRIMARY KEY (CODE_ID, CODE),
  CONSTRAINT FK_CMMN_DTL_CODE FOREIGN KEY (CODE_ID) REFERENCES TB_CMMN_CODE (CODE_ID)
);

-- 권한
CREATE TABLE TB_AUTHOR_INFO (
  AUTHOR_CODE       VARCHAR(30)  NOT NULL,
  AUTHOR_NM         VARCHAR(60)  NOT NULL,
  AUTHOR_DC         VARCHAR(200),
  AUTHOR_CREAT_DE   CHAR(20)     NOT NULL,
  FRST_REGIST_PNTTM TIMESTAMP,
  FRST_REGISTER_ID  VARCHAR(20),
  LAST_UPDT_PNTTM   TIMESTAMP,
  LAST_UPDUSR_ID    VARCHAR(20),
  CONSTRAINT TB_AUTHOR_INFO_PK PRIMARY KEY (AUTHOR_CODE)
);

-- 권한그룹
CREATE TABLE TB_AUTHOR_GROUP_INFO (
  GROUP_ID          CHAR(20)     NOT NULL DEFAULT '',
  GROUP_NM          VARCHAR(60)  NOT NULL,
  GROUP_CREAT_DE    CHAR(20)     NOT NULL,
  GROUP_DC          VARCHAR(100),
  FRST_REGIST_PNTTM TIMESTAMP,
  FRST_REGISTER_ID  VARCHAR(20),
  LAST_UPDT_PNTTM   TIMESTAMP,
  LAST_UPDUSR_ID    VARCHAR(20),
  CONSTRAINT TB_AUTHOR_GROUP_INFO_PK PRIMARY KEY (GROUP_ID)
);

-- 조직
CREATE TABLE TB_ORGNZT_INFO (
  ORGNZT_ID         CHAR(20)     NOT NULL DEFAULT '',
  ORGNZT_NM         VARCHAR(20)  NOT NULL,
  ORGNZT_DC         VARCHAR(100),
  FRST_REGIST_PNTTM TIMESTAMP,
  FRST_REGISTER_ID  VARCHAR(20),
  LAST_UPDT_PNTTM   TIMESTAMP,
  LAST_UPDUSR_ID    VARCHAR(20),
  CONSTRAINT TB_ORGNZT_INFO_PK PRIMARY KEY (ORGNZT_ID)
);

-- 사용자/직원
CREATE TABLE TB_EMPLYR_INFO (
  EMPLYR_ID           VARCHAR(20)  NOT NULL,
  ORGNZT_ID           CHAR(20),
  USER_NM             VARCHAR(60)  NOT NULL,
  PASSWORD            VARCHAR(200) NOT NULL,
  EMPL_NO             VARCHAR(20),
  IHIDNUM             VARCHAR(200),
  SEXDSTN_CODE        CHAR(1),
  BRTHDY              CHAR(20),
  FXNUM               VARCHAR(20),
  HOUSE_ADRES         VARCHAR(100),
  PASSWORD_HINT       VARCHAR(100) NOT NULL,
  PASSWORD_CNSR       VARCHAR(100) NOT NULL,
  HOUSE_END_TELNO     VARCHAR(4),
  AREA_NO             VARCHAR(4),
  DETAIL_ADRES        VARCHAR(100),
  ZIP                 VARCHAR(6),
  OFFM_TELNO          VARCHAR(20),
  MBTLNUM             VARCHAR(20),
  EMAIL_ADRES         VARCHAR(50),
  OFCPS_NM            VARCHAR(60),
  HOUSE_MIDDLE_TELNO  VARCHAR(4),
  GROUP_ID            CHAR(20),
  PSTINST_CODE        CHAR(8),
  EMPLYR_STTUS_CODE   VARCHAR(15)  NOT NULL,
  ESNTL_ID            CHAR(20)     NOT NULL,
  CRTFC_DN_VALUE      VARCHAR(20),
  SBSCRB_DE           TIMESTAMP,
  FRST_REGIST_PNTTM   TIMESTAMP,
  FRST_REGISTER_ID    VARCHAR(20),
  LAST_UPDT_PNTTM     TIMESTAMP,
  LAST_UPDUSR_ID      VARCHAR(20),
  CONSTRAINT TB_EMPLYR_INFO_PK PRIMARY KEY (EMPLYR_ID),
  CONSTRAINT FK_EMPLYR_GROUP  FOREIGN KEY (GROUP_ID) REFERENCES TB_AUTHOR_GROUP_INFO (GROUP_ID) ON DELETE CASCADE,
  CONSTRAINT FK_EMPLYR_ORGNZT FOREIGN KEY (ORGNZT_ID) REFERENCES TB_ORGNZT_INFO (ORGNZT_ID) ON DELETE CASCADE
);

-- 사용자 변경이력
CREATE TABLE TB_EMPLYR_INFO_CHNG_DTLS (
  EMPLYR_ID           VARCHAR(20)  NOT NULL,
  CHANGE_DE           CHAR(20)     NOT NULL,
  ORGNZT_ID           CHAR(20),
  GROUP_ID            CHAR(20),
  EMPL_NO             VARCHAR(20)  NOT NULL,
  SEXDSTN_CODE        CHAR(1),
  BRTHDY              CHAR(20),
  FXNUM               VARCHAR(20),
  HOUSE_ADRES         VARCHAR(100) NOT NULL,
  HOUSE_END_TELNO     VARCHAR(4),
  AREA_NO             VARCHAR(4),
  DETAIL_ADRES        VARCHAR(100) NOT NULL,
  ZIP                 VARCHAR(6)   NOT NULL,
  OFFM_TELNO          VARCHAR(20),
  MBTLNUM             VARCHAR(20)  NOT NULL,
  EMAIL_ADRES         VARCHAR(50),
  HOUSE_MIDDLE_TELNO  VARCHAR(4),
  PSTINST_CODE        CHAR(8),
  EMPLYR_STTUS_CODE   VARCHAR(15)  NOT NULL,
  ESNTL_ID            CHAR(20),
  FRST_REGIST_PNTTM   TIMESTAMP,
  FRST_REGISTER_ID    VARCHAR(20),
  LAST_UPDT_PNTTM     TIMESTAMP,
  LAST_UPDUSR_ID      VARCHAR(20),
  CONSTRAINT TB_EMPLYR_INFO_CHNG_DTLS_PK PRIMARY KEY (EMPLYR_ID, CHANGE_DE),
  CONSTRAINT FK_CHNG_EMPLYR FOREIGN KEY (EMPLYR_ID) REFERENCES TB_EMPLYR_INFO (EMPLYR_ID)
);

-- 사용자 보안 설정
CREATE TABLE TB_EMPLYR_SCRTY_ESTBS (
  SCRTY_DTRMN_TRGET_ID VARCHAR(20)  NOT NULL,
  MBER_TY_CODE         VARCHAR(15),
  AUTHOR_CODE          VARCHAR(30)  NOT NULL,
  FRST_REGIST_PNTTM    TIMESTAMP,
  FRST_REGISTER_ID     VARCHAR(20),
  LAST_UPDT_PNTTM      TIMESTAMP,
  LAST_UPDUSR_ID       VARCHAR(20),
  CONSTRAINT TB_EMPLYR_SCRTY_ESTBS_PK PRIMARY KEY (SCRTY_DTRMN_TRGET_ID),
  CONSTRAINT FK_SCRTY_AUTHOR  FOREIGN KEY (AUTHOR_CODE) REFERENCES TB_AUTHOR_INFO (AUTHOR_CODE)
);

-- 일반회원
CREATE TABLE TB_GNRL_MBER (
  MBER_ID           VARCHAR(20)  NOT NULL DEFAULT '',
  PASSWORD          VARCHAR(200) NOT NULL,
  PASSWORD_HINT     VARCHAR(100),
  PASSWORD_CNSR     VARCHAR(100),
  IHIDNUM           VARCHAR(200),
  MBER_NM           VARCHAR(50)  NOT NULL,
  ZIP               VARCHAR(6),
  ADRES             VARCHAR(100),
  AREA_NO           VARCHAR(4),
  MBER_STTUS        VARCHAR(15),
  DETAIL_ADRES      VARCHAR(100),
  END_TELNO         VARCHAR(4),
  MBTLNUM           VARCHAR(20),
  GROUP_ID          CHAR(20),
  MBER_FXNUM        VARCHAR(20),
  MBER_EMAIL_ADRES  VARCHAR(50),
  MIDDLE_TELNO      VARCHAR(4),
  SBSCRB_DE         TIMESTAMP,
  SEXDSTN_CODE      CHAR(1),
  ESNTL_ID          CHAR(20)     NOT NULL,
  FRST_REGIST_PNTTM TIMESTAMP,
  FRST_REGISTER_ID  VARCHAR(20),
  LAST_UPDT_PNTTM   TIMESTAMP,
  LAST_UPDUSR_ID    VARCHAR(20),
  CONSTRAINT TB_GNRL_MBER_PK PRIMARY KEY (MBER_ID),
  CONSTRAINT FK_GNRL_MBER_GROUP FOREIGN KEY (GROUP_ID) REFERENCES TB_AUTHOR_GROUP_INFO (GROUP_ID) ON DELETE CASCADE
);

-- 기업회원
CREATE TABLE TB_ENTRPRS_MBER (
  ENTRPRS_MBER_ID             VARCHAR(20)  NOT NULL DEFAULT '',
  ENTRPRS_SE_CODE             CHAR(15),
  BIZRNO                      VARCHAR(10),
  JURIRNO                     VARCHAR(13),
  CMPNY_NM                    VARCHAR(60)  NOT NULL,
  CXFC                        VARCHAR(50),
  ZIP                         VARCHAR(6),
  ADRES                       VARCHAR(100),
  ENTRPRS_MIDDLE_TELNO        VARCHAR(4),
  FXNUM                       VARCHAR(20),
  INDUTY_CODE                 CHAR(15),
  APPLCNT_NM                  VARCHAR(50)  NOT NULL,
  APPLCNT_IHIDNUM             VARCHAR(200),
  SBSCRB_DE                   TIMESTAMP,
  ENTRPRS_MBER_STTUS          VARCHAR(15),
  ENTRPRS_MBER_PASSWORD       VARCHAR(200),
  ENTRPRS_MBER_PASSWORD_HINT  VARCHAR(100) NOT NULL,
  ENTRPRS_MBER_PASSWORD_CNSR  VARCHAR(100) NOT NULL,
  GROUP_ID                    CHAR(20),
  DETAIL_ADRES                VARCHAR(100),
  ENTRPRS_END_TELNO           VARCHAR(4),
  AREA_NO                     VARCHAR(4),
  APPLCNT_EMAIL_ADRES         VARCHAR(50),
  ESNTL_ID                    CHAR(20)     NOT NULL,
  FRST_REGIST_PNTTM           TIMESTAMP,
  FRST_REGISTER_ID            VARCHAR(20),
  LAST_UPDT_PNTTM             TIMESTAMP,
  LAST_UPDUSR_ID              VARCHAR(20),
  CONSTRAINT TB_ENTRPRS_MBER_PK PRIMARY KEY (ENTRPRS_MBER_ID),
  CONSTRAINT FK_ENTRPRS_GROUP FOREIGN KEY (GROUP_ID) REFERENCES TB_AUTHOR_GROUP_INFO (GROUP_ID) ON DELETE CASCADE
);

ALTER TABLE TB_EMPLYR_SCRTY_ESTBS ADD CONSTRAINT FK_SCRTY_EMPLYR   FOREIGN KEY (SCRTY_DTRMN_TRGET_ID) REFERENCES TB_EMPLYR_INFO (EMPLYR_ID);
ALTER TABLE TB_EMPLYR_SCRTY_ESTBS ADD CONSTRAINT FK_SCRTY_ENTRPRS  FOREIGN KEY (SCRTY_DTRMN_TRGET_ID) REFERENCES TB_ENTRPRS_MBER (ENTRPRS_MBER_ID);
ALTER TABLE TB_EMPLYR_SCRTY_ESTBS ADD CONSTRAINT FK_SCRTY_GNRL     FOREIGN KEY (SCRTY_DTRMN_TRGET_ID) REFERENCES TB_GNRL_MBER (MBER_ID);

-- 게시판 마스터
CREATE TABLE TB_BBS_MASTER (
  BBS_ID                  CHAR(20)      NOT NULL,
  BBS_NM                  VARCHAR(255)  NOT NULL,
  BBS_INTRCN              VARCHAR(2400),
  BBS_TY_CODE             CHAR(6)       NOT NULL,
  BBS_ATTRB_CODE          CHAR(6)       NOT NULL,
  REPLY_POSBL_AT          CHAR(1),
  FILE_ATCH_POSBL_AT      CHAR(1)       NOT NULL,
  ATCH_POSBL_FILE_NUMBER  NUMERIC(2)    NOT NULL,
  ATCH_POSBL_FILE_SIZE    NUMERIC(8),
  USE_AT                  CHAR(1)       NOT NULL,
  TMPLAT_ID               CHAR(20),
  FRST_REGIST_PNTTM       TIMESTAMP     NOT NULL,
  FRST_REGISTER_ID        VARCHAR(20)   NOT NULL,
  LAST_UPDT_PNTTM         TIMESTAMP,
  LAST_UPDUSR_ID          VARCHAR(20),
  CONSTRAINT TB_BBS_MASTER_PK PRIMARY KEY (BBS_ID)
);

-- 게시판 옵션
CREATE TABLE TB_BBS_MASTER_OPTN (
  BBS_ID            CHAR(20)     NOT NULL DEFAULT '',
  ANSWER_AT         CHAR(1)      NOT NULL DEFAULT '',
  STSFDG_AT         CHAR(1)      NOT NULL DEFAULT '',
  FRST_REGIST_PNTTM TIMESTAMP    NOT NULL DEFAULT '1970-01-01 00:00:00',
  FRST_REGISTER_ID  VARCHAR(20)  NOT NULL DEFAULT '',
  LAST_UPDT_PNTTM   TIMESTAMP,
  LAST_UPDUSR_ID    VARCHAR(20),
  CONSTRAINT TB_BBS_MASTER_OPTN_PK PRIMARY KEY (BBS_ID)
);

-- 게시판 사용 대상
CREATE TABLE TB_BBS_USE (
  BBS_ID            CHAR(20)     NOT NULL,
  TRGET_ID          CHAR(20)     NOT NULL DEFAULT '',
  USE_AT            CHAR(1)      NOT NULL,
  REGIST_SE_CODE    CHAR(6),
  FRST_REGIST_PNTTM TIMESTAMP,
  FRST_REGISTER_ID  VARCHAR(20)  NOT NULL,
  LAST_UPDT_PNTTM   TIMESTAMP,
  LAST_UPDUSR_ID    VARCHAR(20),
  CONSTRAINT TB_BBS_USE_PK PRIMARY KEY (BBS_ID, TRGET_ID),
  CONSTRAINT FK_BBS_USE_MASTER FOREIGN KEY (BBS_ID) REFERENCES TB_BBS_MASTER (BBS_ID)
);

-- 게시물
CREATE TABLE TB_BBS (
  NTT_ID            NUMERIC(20)   NOT NULL,
  BBS_ID            CHAR(20)      NOT NULL,
  NTT_NO            NUMERIC(20),
  NTT_SJ            VARCHAR(2000),
  NTT_CN            TEXT,
  ANSWER_AT         CHAR(1),
  PARNTSCTT_NO      NUMERIC(10),
  ANSWER_LC         INTEGER,
  SORT_ORDR         NUMERIC(8),
  RDCNT             NUMERIC(10),
  USE_AT            CHAR(1)       NOT NULL,
  NTCE_BGNDE        CHAR(20),
  NTCE_ENDDE        CHAR(20),
  NTCR_ID           VARCHAR(20),
  NTCR_NM           VARCHAR(20),
  PASSWORD          VARCHAR(200),
  ATCH_FILE_ID      CHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP     NOT NULL,
  FRST_REGISTER_ID  VARCHAR(20)   NOT NULL,
  LAST_UPDT_PNTTM   TIMESTAMP,
  LAST_UPDUSR_ID    VARCHAR(20),
  CONSTRAINT TB_BBS_PK PRIMARY KEY (NTT_ID, BBS_ID),
  CONSTRAINT FK_BBS_MASTER FOREIGN KEY (BBS_ID) REFERENCES TB_BBS_MASTER (BBS_ID)
);

-- 첨부파일 헤더
CREATE TABLE TB_FILE (
  ATCH_FILE_ID      CHAR(20)     NOT NULL,
  CREAT_DT          TIMESTAMP    NOT NULL,
  USE_AT            CHAR(1),
  FRST_REGIST_PNTTM TIMESTAMP,
  FRST_REGISTER_ID  VARCHAR(20),
  LAST_UPDT_PNTTM   TIMESTAMP,
  LAST_UPDUSR_ID    VARCHAR(20),
  CONSTRAINT TB_FILE_PK PRIMARY KEY (ATCH_FILE_ID)
);

-- 첨부파일 상세
CREATE TABLE TB_FILE_DETAIL (
  ATCH_FILE_ID      CHAR(20)      NOT NULL,
  FILE_SN           NUMERIC(10)   NOT NULL,
  FILE_STRE_COURS   VARCHAR(2000) NOT NULL,
  STRE_FILE_NM      VARCHAR(255)  NOT NULL,
  ORIGNL_FILE_NM    VARCHAR(255),
  FILE_EXTSN        VARCHAR(20)   NOT NULL,
  FILE_CN           TEXT,
  FILE_SIZE         NUMERIC(8),
  FRST_REGIST_PNTTM TIMESTAMP,
  FRST_REGISTER_ID  VARCHAR(20),
  LAST_UPDT_PNTTM   TIMESTAMP,
  LAST_UPDUSR_ID    VARCHAR(20),
  CONSTRAINT TB_FILE_DETAIL_PK PRIMARY KEY (ATCH_FILE_ID, FILE_SN),
  CONSTRAINT FK_FILE_DETAIL FOREIGN KEY (ATCH_FILE_ID) REFERENCES TB_FILE (ATCH_FILE_ID)
);

-- 일정
CREATE TABLE TB_SCHDUL_INFO (
  SCHDUL_ID         CHAR(20)      NOT NULL,
  SCHDUL_SE         CHAR(1),
  SCHDUL_DEPT_ID    VARCHAR(20),
  SCHDUL_KND_CODE   VARCHAR(20),
  SCHDUL_BEGINDE    TIMESTAMP,
  SCHDUL_ENDDE      TIMESTAMP,
  SCHDUL_NM         VARCHAR(255),
  SCHDUL_CN         VARCHAR(2500),
  SCHDUL_PLACE      VARCHAR(255),
  SCHDUL_IPCR_CODE  CHAR(1),
  SCHDUL_CHARGER_ID VARCHAR(20),
  ATCH_FILE_ID      CHAR(20),
  REPTIT_SE_CODE    CHAR(3),
  FRST_REGIST_PNTTM TIMESTAMP,
  FRST_REGISTER_ID  VARCHAR(20),
  LAST_UPDT_PNTTM   TIMESTAMP,
  LAST_UPDUSR_ID    VARCHAR(20),
  CONSTRAINT TB_SCHDUL_INFO_PK PRIMARY KEY (SCHDUL_ID)
);

-- 뷰
CREATE OR REPLACE VIEW VW_USER_MASTER (
  ESNTL_ID, USER_ID, PASSWORD, USER_NM, USER_ZIP, USER_ADRES,
  USER_EMAIL, GROUP_ID, USER_SE, ORGNZT_ID
) AS
  SELECT ESNTL_ID, MBER_ID, PASSWORD, MBER_NM, ZIP, ADRES,
         MBER_EMAIL_ADRES, ' ', 'GNR', ' '
    FROM TB_GNRL_MBER
  UNION ALL
  SELECT ESNTL_ID, EMPLYR_ID, PASSWORD, USER_NM, ZIP, HOUSE_ADRES,
         EMAIL_ADRES, GROUP_ID, 'USR', ORGNZT_ID
    FROM TB_EMPLYR_INFO
  UNION ALL
  SELECT ESNTL_ID, ENTRPRS_MBER_ID, ENTRPRS_MBER_PASSWORD, CMPNY_NM,
         ZIP, ADRES, APPLCNT_EMAIL_ADRES, ' ', 'ENT', ' '
    FROM TB_ENTRPRS_MBER;

-- ============================================================
-- 커뮤니티/동호회/약관/다이어리 (기능 유지 — 표준 TB_ 명명 + 감사컬럼)
-- ============================================================
DROP TABLE IF EXISTS TB_CMMNTY_USER CASCADE;
DROP TABLE IF EXISTS TB_CLUB_USER CASCADE;
DROP TABLE IF EXISTS TB_CMMNTY CASCADE;
DROP TABLE IF EXISTS TB_CLUB CASCADE;
DROP TABLE IF EXISTS TB_STPLAT_INFO CASCADE;
DROP TABLE IF EXISTS TB_DIARY_INFO CASCADE;
CREATE TABLE TB_CMMNTY (
  CMMNTY_ID         VARCHAR(20) NOT NULL,
  CMMNTY_NM         VARCHAR(60),
  USE_AT            CHAR(1),
  FRST_REGIST_PNTTM TIMESTAMP, FRST_REGISTER_ID VARCHAR(20), LAST_UPDT_PNTTM TIMESTAMP, LAST_UPDUSR_ID VARCHAR(20),
  CONSTRAINT TB_CMMNTY_PK PRIMARY KEY (CMMNTY_ID)
);
CREATE TABLE TB_CMMNTY_USER (
  ESNTL_ID          VARCHAR(20) NOT NULL,
  CMMNTY_ID         VARCHAR(20),
  EMPLYR_ID         VARCHAR(20),
  MNGR_AT           CHAR(1),
  USE_AT            CHAR(1),
  REGIST_SE_CODE    VARCHAR(6),
  FRST_REGIST_PNTTM TIMESTAMP, FRST_REGISTER_ID VARCHAR(20), LAST_UPDT_PNTTM TIMESTAMP, LAST_UPDUSR_ID VARCHAR(20),
  CONSTRAINT TB_CMMNTY_USER_PK PRIMARY KEY (ESNTL_ID)
);
CREATE TABLE TB_CLUB (
  CLB_ID            VARCHAR(20) NOT NULL,
  CLB_NM            VARCHAR(60),
  USE_AT            CHAR(1),
  FRST_REGIST_PNTTM TIMESTAMP, FRST_REGISTER_ID VARCHAR(20), LAST_UPDT_PNTTM TIMESTAMP, LAST_UPDUSR_ID VARCHAR(20),
  CONSTRAINT TB_CLUB_PK PRIMARY KEY (CLB_ID)
);
CREATE TABLE TB_CLUB_USER (
  ESNTL_ID          VARCHAR(20) NOT NULL,
  CLB_ID            VARCHAR(20),
  EMPLYR_ID         VARCHAR(20),
  OPRTR_AT          CHAR(1),
  USE_AT            CHAR(1),
  REGIST_SE_CODE    VARCHAR(6),
  FRST_REGIST_PNTTM TIMESTAMP, FRST_REGISTER_ID VARCHAR(20), LAST_UPDT_PNTTM TIMESTAMP, LAST_UPDUSR_ID VARCHAR(20),
  CONSTRAINT TB_CLUB_USER_PK PRIMARY KEY (ESNTL_ID)
);
CREATE TABLE TB_STPLAT_INFO (
  USE_STPLAT_ID     VARCHAR(20) NOT NULL,
  USE_STPLAT_NM     VARCHAR(100),
  USE_STPLAT_CN     VARCHAR(4000),
  INFO_PROVD_AGRE_CN VARCHAR(4000),
  FRST_REGIST_PNTTM TIMESTAMP, FRST_REGISTER_ID VARCHAR(20), LAST_UPDT_PNTTM TIMESTAMP, LAST_UPDUSR_ID VARCHAR(20),
  CONSTRAINT TB_STPLAT_INFO_PK PRIMARY KEY (USE_STPLAT_ID)
);
CREATE TABLE TB_DIARY_INFO (
  DIARY_ID          VARCHAR(20) NOT NULL,
  SCHDUL_ID         VARCHAR(20),
  DIARY_CN          VARCHAR(2500),
  FRST_REGIST_PNTTM TIMESTAMP, FRST_REGISTER_ID VARCHAR(20), LAST_UPDT_PNTTM TIMESTAMP, LAST_UPDUSR_ID VARCHAR(20),
  CONSTRAINT TB_DIARY_INFO_PK PRIMARY KEY (DIARY_ID)
);

-- 개정이력: 2026.06.17  구재호  커뮤니티/동호회/약관/다이어리 TB_ 테이블 추가
